# Generated by Django 2.0 on 2018-01-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10, verbose_name='书本序号')),
                ('book_name', models.CharField(max_length=20, verbose_name='书名')),
                ('book_star', models.CharField(max_length=5, verbose_name='评分')),
                ('people_num', models.CharField(max_length=10, verbose_name='评价人数')),
                ('author_info', models.CharField(max_length=20, verbose_name='作者')),
                ('book_publish', models.CharField(max_length=20, verbose_name='出版社')),
                ('book_publish_time', models.CharField(max_length=10, verbose_name='出版年')),
                ('book_quote', models.CharField(max_length=2000, verbose_name='内容简介')),
                ('author_quote', models.CharField(max_length=2000, verbose_name='作者介绍')),
                ('image_urls', models.CharField(max_length=100, verbose_name='书本封面')),
            ],
            options={
                'ordering': ['book_id'],
            },
        ),
    ]
